### ISSUE TITLE
Issue in medium-mslp-rain notebook

### ISSUE THREAD

**Issue by clausmichele** [ecmwf/notebook-examples#10]
### What happened?

I tried the [medium-mslp-rain.ipynb](https://github.com/ecmwf/notebook-examples/blob/master/opencharts/medium-mslp-rain.ipynb) notebook with Binder, and when computing the total precipitation between steps 12 24 UTC it returns a TypeError:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[22], line 3
      1 tp = (tp_24 - tp_12)
----> 3 tp.ls()

File /srv/conda/envs/notebook/lib/python3.10/site-packages/metview/metviewpy/fieldset.py:774, in Fieldset.ls(self, **kwargs)
    773 def ls(self, **kwargs):
--> 774     return self._get_db().ls(**kwargs)

File /srv/conda/envs/notebook/lib/python3.10/site-packages/metview/metviewpy/indexdb.py:465, in FieldsetDb.ls(self, extra_keys, filter, no_print)
    463 keys = list(ls_keys)
    464 keys.append("_msgIndex1")
--> 465 df = df[keys]
    466 df = df.sort_values("_msgIndex1")
    467 df = df.rename(columns={"_msgIndex1": "Message"})

TypeError: 'NoneType' object is not subscriptable
```

### What are the steps to reproduce the bug?

Run the notebook with Binder as is.

### Version

Latest

### Platform (OS and architecture)

Binder

### Organisation

Eurac Research

**Comment by milanavuckovic** [comment]
Hi Michele,
Unfortunately libraries used in these notebooks (ecmwf.data and magpy) are now becoming old and are not maintained. Internally we are replacing them with new libraries that rely on xarray, numpy, cartopy and matplotlib.
However those are not ready yet.
I am planning to update the notebooks to use Metview which is used operationally to produce the charts until the new libraries are ready.
Sorry for the inconvenience.
