### ISSUE TITLE
Wrong filepath in mybinder

### ISSUE THREAD

**Issue by yuriishizawa** [ecmwf/notebook-examples#5]
The MyBinder's url is forwarding to a wrong `filepath` (/home/jovya) in jupyter.

**Comment by yuriishizawa** [comment]
Closing issue due to fix applied by @milanavuckovic in [this commit](https://github.com/ecmwf/notebook-examples/commit/e630d6e68fa186d294546e137c859781925caa3f).

**Comment by milanavuckovic** [comment]
Hi Yuri, 
Thank you for your comment and pull request! I needed to do bigger changes to the requirement file and fixed the binder url along the way. Sorry for not merging your PR!
I am due to big review and refactor of this repo soon. I do hope it is useful :)
