### ISSUE TITLE
plotting error 

### ISSUE THREAD

**Issue by basitkhanNZ** [ecmwf/notebook-examples#9]
Hi there,
I am a new Bee and trying to plot ecmwf forecast chart using the notebook script for 850 Temp and 500 Geopotential height, but getting the following error. I already downloaded the api key and code runs fine until it comes to the plotting functions where  i get the following errors,

Any help in fixing the error will be greatly appreciated. 

Cheers,
Basit

proj_create: /home/bak8122/.conda/envs/op13/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 3 is expected. It comes from another PROJ installation.
proj_create: no database context specified
EXCEPTION in py_coast(): ProjP: cannot create crs to crs from [EPSG:4326] to [+proj=stere +lat_0=90 +lat_ts=90  +lon_0=0 +k=0.994 +x_0=2000000 +y_0=2000000   +datum=WGS84 +units=m]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bak8122/.conda/envs/op13/lib/python3.11/site-packages/magpye/geomap.py", line 607, in show
    return self._execute()
           ^^^^^^^^^^^^^^^
  File "/home/bak8122/.conda/envs/op13/lib/python3.11/site-packages/magpye/geomap.py", line 628, in _execute
    result = magics.plot(*(macro.execute() for macro in queue))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bak8122/.conda/envs/op13/lib/python3.11/site-packages/Magics/macro.py", line 701, in plot
    return _plot(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bak8122/.conda/envs/op13/lib/python3.11/site-packages/Magics/macro.py", line 591, in _plot
    _execute(n)
  File "/home/bak8122/.conda/envs/op13/lib/python3.11/site-packages/Magics/macro.py", line 569, in _execute
    o.execute()
  File "/home/bak8122/.conda/envs/op13/lib/python3.11/site-packages/Magics/macro.py", line 290, in execute
    self.action()
  File "/home/bak8122/.conda/envs/op13/lib/python3.11/site-packages/Magics/Magics.py", line 132, in wrapped
    raise MagicsError(char_to_string(err))
Magics.Magics.MagicsError: ProjP: cannot create crs to crs from [EPSG:4326] to [+proj=stere +lat_0=90 +lat_ts=90  +lon_0=0 +k=0.994 +x_0=2000000 +y_0=2000000   +datum=WGS84 +units=m]

**Comment by milanavuckovic** [comment]
Hi Basit,
The libraries used for data processing and visualisation in these notebooks were experimental and will need to be updated.
I expect to update the notebooks to use the new libraries during the summer this year. 
They will be using the new [earthkit-maps library](https://earthkit-maps.readthedocs.io/en/latest/).
You can also have a look at our [Metview library](https://metview.readthedocs.io/en/latest/index.html) for plotting the grib data.
Sorry for the inconvenience.

**Comment by basitkhanNZ** [comment]
Dear Milanavuckoiv,

Many thanks for the quick response. The information was quite helpful,
specially  about the metview application. I installed it on my laptop and
watched a few webinars on its application and capabilities by ECMWF
colleagues. Its amazing utility. The documentation says metview it can also
handle netCDF data, i wonder if it has the same capabilities and
convenience for netCDF data as it has for Grib data?

Thanks again and I look forward to the updated scripts.

best wishes,
Basit
-----
Basit Khan, PhD.
Research Scientist
Mubadala Arabian Center for Climate and Environmental Sciences (ACCESS).
New York University, Abu Dhabi
Abu Dhabi 129188, UAE.

**Comment by milanavuckovic** [comment]
Dear Basit,
The capabilities of Metview are indeed not the same for NetCDF data as for GRIB data. I can recommend [xarray](https://docs.xarray.dev/en/stable/user-guide/io.html) for the NetCDF data.
Best regards,
Milana
